using System;

namespace GloboWeather.WeatherManagement.Application.Models.Weather
{
    public class BaseModelWeather
    {
        public string DiemId { get; set; }
        public DateTime RefDate { get; set; }
        public int? _1 { get; set; }
        public int? _2 { get; set; }
        public int? _3 { get; set; }
        public int? _4 { get; set; }
        public int? _5 { get; set; }
        public int? _6 { get; set; }
        public int? _7 { get; set; }
        public int? _8 { get; set; }
        public int? _9 { get; set; }
        public int? _10 { get; set; }
        public int? _11 { get; set; }
        public int? _12 { get; set; }
        public int? _13 { get; set; }
        public int? _14 { get; set; }
        public int? _15 { get; set; }
        public int? _16 { get; set; }
        public int? _17 { get; set; }
        public int? _18 { get; set; }
        public int? _19 { get; set; }
        public int? _20 { get; set; }
        public int? _21 { get; set; }
        public int? _22 { get; set; }
        public int? _23 { get; set; }
        public int? _24 { get; set; }
        public int? _25 { get; set; }
        public int? _26 { get; set; }
        public int? _27 { get; set; }
        public int? _28 { get; set; }
        public int? _29 { get; set; }
        public int? _30 { get; set; }
        public int? _31 { get; set; }
        public int? _32 { get; set; }
        public int? _33 { get; set; }
        public int? _34 { get; set; }
        public int? _35 { get; set; }
        public int? _36 { get; set; }
        public int? _37 { get; set; }
        public int? _38 { get; set; }
        public int? _39 { get; set; }
        public int? _40 { get; set; }
        public int? _41 { get; set; }
        public int? _42 { get; set; }
        public int? _43 { get; set; }
        public int? _44 { get; set; }
        public int? _45 { get; set; }
        public int? _46 { get; set; }
        public int? _47 { get; set; }
        public int? _48 { get; set; }
        public int? _49 { get; set; }
        public int? _50 { get; set; }
        public int? _51 { get; set; }
        public int? _52 { get; set; }
        public int? _53 { get; set; }
        public int? _54 { get; set; }
        public int? _55 { get; set; }
        public int? _56 { get; set; }
        public int? _57 { get; set; }
        public int? _58 { get; set; }
        public int? _59 { get; set; }
        public int? _60 { get; set; }
        public int? _61 { get; set; }
        public int? _62 { get; set; }
        public int? _63 { get; set; }
        public int? _64 { get; set; }
        public int? _65 { get; set; }
        public int? _66 { get; set; }
        public int? _67 { get; set; }
        public int? _68 { get; set; }
        public int? _69 { get; set; }
        public int? _70 { get; set; }
        public int? _71 { get; set; }
        public int? _72 { get; set; }
        public int? _73 { get; set; }
        public int? _74 { get; set; }
        public int? _75 { get; set; }
        public int? _76 { get; set; }
        public int? _77 { get; set; }
        public int? _78 { get; set; }
        public int? _79 { get; set; }
        public int? _80 { get; set; }
        public int? _81 { get; set; }
        public int? _82 { get; set; }
        public int? _83 { get; set; }
        public int? _84 { get; set; }
        public int? _85 { get; set; }
        public int? _86 { get; set; }
        public int? _87 { get; set; }
        public int? _88 { get; set; }
        public int? _89 { get; set; }
        public int? _90 { get; set; }
        public int? _91 { get; set; }
        public int? _92 { get; set; }
        public int? _93 { get; set; }
        public int? _94 { get; set; }
        public int? _95 { get; set; }
        public int? _96 { get; set; }
        public int? _97 { get; set; }
        public int? _98 { get; set; }
        public int? _99 { get; set; }
        public int? _100 { get; set; }
        public int? _101 { get; set; }
        public int? _102 { get; set; }
        public int? _103 { get; set; }
        public int? _104 { get; set; }
        public int? _105 { get; set; }
        public int? _106 { get; set; }
        public int? _107 { get; set; }
        public int? _108 { get; set; }
        public int? _109 { get; set; }
        public int? _110 { get; set; }
        public int? _111 { get; set; }
        public int? _112 { get; set; }
        public int? _113 { get; set; }
        public int? _114 { get; set; }
        public int? _115 { get; set; }
        public int? _116 { get; set; }
        public int? _117 { get; set; }
        public int? _118 { get; set; }
        public int? _119 { get; set; }
        public int? _120 { get; set; }
    }
}