using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GloboWeather.WeatherManagement.Application.Models.Weather.WindDirection
{
    public partial class WindDirectionResponse
    {
        public string DiemId { get; set; }
        public DateTime RefDate { get; set; }
        public string _1 { get; set; }
        public string _2 { get; set; }
        public string _3 { get; set; }
        public string _4 { get; set; }
        public string _5 { get; set; }
        public string _6 { get; set; }
        public string _7 { get; set; }
        public string _8 { get; set; }
        public string _9 { get; set; }
        public string _10 { get; set; }
        public string _11 { get; set; }
        public string _12 { get; set; }
        public string _13 { get; set; }
        public string _14 { get; set; }
        public string _15 { get; set; }
        public string _16 { get; set; }
        public string _17 { get; set; }
        public string _18 { get; set; }
        public string _19 { get; set; }
        public string _20 { get; set; }
        public string _21 { get; set; }
        public string _22 { get; set; }
        public string _23 { get; set; }
        public string _24 { get; set; }
        public string _25 { get; set; }
        public string _26 { get; set; }
        public string _27 { get; set; }
        public string _28 { get; set; }
        public string _29 { get; set; }
        public string _30 { get; set; }
        public string _31 { get; set; }
        public string _32 { get; set; }
        public string _33 { get; set; }
        public string _34 { get; set; }
        public string _35 { get; set; }
        public string _36 { get; set; }
        public string _37 { get; set; }
        public string _38 { get; set; }
        public string _39 { get; set; }
        public string _40 { get; set; }
        public string _41 { get; set; }
        public string _42 { get; set; }
        public string _43 { get; set; }
        public string _44 { get; set; }
        public string _45 { get; set; }
        public string _46 { get; set; }
        public string _47 { get; set; }
        public string _48 { get; set; }
        public string _49 { get; set; }
        public string _50 { get; set; }
        public string _51 { get; set; }
        public string _52 { get; set; }
        public string _53 { get; set; }
        public string _54 { get; set; }
        public string _55 { get; set; }
        public string _56 { get; set; }
        public string _57 { get; set; }
        public string _58 { get; set; }
        public string _59 { get; set; }
        public string _60 { get; set; }
        public string _61 { get; set; }
        public string _62 { get; set; }
        public string _63 { get; set; }
        public string _64 { get; set; }
        public string _65 { get; set; }
        public string _66 { get; set; }
        public string _67 { get; set; }
        public string _68 { get; set; }
        public string _69 { get; set; }
        public string _70 { get; set; }
        public string _71 { get; set; }
        public string _72 { get; set; }
        public string _73 { get; set; }
        public string _74 { get; set; }
        public string _75 { get; set; }
        public string _76 { get; set; }
        public string _77 { get; set; }
        public string _78 { get; set; }
        public string _79 { get; set; }
        public string _80 { get; set; }
        public string _81 { get; set; }
        public string _82 { get; set; }
        public string _83 { get; set; }
        public string _84 { get; set; }
        public string _85 { get; set; }
        public string _86 { get; set; }
        public string _87 { get; set; }
        public string _88 { get; set; }
        public string _89 { get; set; }
        public string _90 { get; set; }
        public string _91 { get; set; }
        public string _92 { get; set; }
        public string _93 { get; set; }
        public string _94 { get; set; }
        public string _95 { get; set; }
        public string _96 { get; set; }
        public string _97 { get; set; }
        public string _98 { get; set; }
        public string _99 { get; set; }
        public string _100 { get; set; }
        public string _101 { get; set; }
        public string _102 { get; set; }
        public string _103 { get; set; }
        public string _104 { get; set; }
        public string _105 { get; set; }
        public string _106 { get; set; }
        public string _107 { get; set; }
        public string _108 { get; set; }
        public string _109 { get; set; }
        public string _110 { get; set; }
        public string _111 { get; set; }
        public string _112 { get; set; }
        public string _113 { get; set; }
        public string _114 { get; set; }
        public string _115 { get; set; }
        public string _116 { get; set; }
        public string _117 { get; set; }
        public string _118 { get; set; }
        public string _119 { get; set; }
        public string _120 { get; set; }
    }
}
