// <auto-generated />
using System;
using GloboWeather.WeatherManagement.Weather.weathercontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GloboWeather.WeatherManagement.Weather.Migrations
{
    [DbContext(typeof(thoitietContext))]
    [Migration("20210524144234_RefDateIntoNhietdo")]
    partial class RefDateIntoNhietdo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Capgio", b =>
                {
                    b.Property<int?>("Color")
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<float?>("WaveM")
                        .HasColumnName("Wave(m)")
                        .HasColumnType("float");

                    b.Property<float?>("WindMS")
                        .HasColumnName("Wind(m/s)")
                        .HasColumnType("float");

                    b.ToTable("capgio");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Diemdubao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Ten")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<float?>("X")
                        .HasColumnType("float");

                    b.Property<float?>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("diemdubao");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Htthoitiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<byte?>("Dem")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte?>("Ngay")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<byte?>("_24h")
                        .HasColumnName("24h")
                        .HasColumnType("tinyint(3) unsigned");

                    b.HasKey("Id");

                    b.ToTable("htthoitiet");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Icon24", b =>
                {
                    b.Property<string>("Icon")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Index")
                        .HasColumnType("int(11)");

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Icon")
                        .HasName("PRIMARY");

                    b.ToTable("icon24");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Icondem", b =>
                {
                    b.Property<string>("Icon")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Icon")
                        .HasName("PRIMARY");

                    b.ToTable("icondem");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Iconngay", b =>
                {
                    b.Property<string>("Icon")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Icon")
                        .HasName("PRIMARY");

                    b.ToTable("iconngay");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Iconthoitiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("iconthoitiet");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.May", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<byte?>("Dem")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte?>("Ngay")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<byte?>("_24h")
                        .HasColumnName("24h")
                        .HasColumnType("tinyint(3) unsigned");

                    b.HasKey("Id");

                    b.ToTable("may");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Mua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<byte?>("Dem")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte?>("Ngay")
                        .HasColumnType("tinyint(3) unsigned");

                    b.Property<byte?>("_24h")
                        .HasColumnName("24h")
                        .HasColumnType("tinyint(3) unsigned");

                    b.HasKey("Id");

                    b.ToTable("mua");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Nhietdo", b =>
                {
                    b.Property<string>("DiemId")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("RefDate")
                        .HasColumnName("RefDate")
                        .HasColumnType("date");

                    b.Property<int?>("_1")
                        .HasColumnName("1")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_10")
                        .HasColumnName("10")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_100")
                        .HasColumnName("100")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_101")
                        .HasColumnName("101")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_102")
                        .HasColumnName("102")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_103")
                        .HasColumnName("103")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_104")
                        .HasColumnName("104")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_105")
                        .HasColumnName("105")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_106")
                        .HasColumnName("106")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_107")
                        .HasColumnName("107")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_108")
                        .HasColumnName("108")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_109")
                        .HasColumnName("109")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_11")
                        .HasColumnName("11")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_110")
                        .HasColumnName("110")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_111")
                        .HasColumnName("111")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_112")
                        .HasColumnName("112")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_113")
                        .HasColumnName("113")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_114")
                        .HasColumnName("114")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_115")
                        .HasColumnName("115")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_116")
                        .HasColumnName("116")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_117")
                        .HasColumnName("117")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_118")
                        .HasColumnName("118")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_119")
                        .HasColumnName("119")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_12")
                        .HasColumnName("12")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_120")
                        .HasColumnName("120")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_13")
                        .HasColumnName("13")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_14")
                        .HasColumnName("14")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_15")
                        .HasColumnName("15")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_16")
                        .HasColumnName("16")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_17")
                        .HasColumnName("17")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_18")
                        .HasColumnName("18")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_19")
                        .HasColumnName("19")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_2")
                        .HasColumnName("2")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_20")
                        .HasColumnName("20")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_21")
                        .HasColumnName("21")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_22")
                        .HasColumnName("22")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_23")
                        .HasColumnName("23")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_24")
                        .HasColumnName("24")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_25")
                        .HasColumnName("25")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_26")
                        .HasColumnName("26")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_27")
                        .HasColumnName("27")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_28")
                        .HasColumnName("28")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_29")
                        .HasColumnName("29")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_3")
                        .HasColumnName("3")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_30")
                        .HasColumnName("30")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_31")
                        .HasColumnName("31")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_32")
                        .HasColumnName("32")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_33")
                        .HasColumnName("33")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_34")
                        .HasColumnName("34")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_35")
                        .HasColumnName("35")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_36")
                        .HasColumnName("36")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_37")
                        .HasColumnName("37")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_38")
                        .HasColumnName("38")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_39")
                        .HasColumnName("39")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_4")
                        .HasColumnName("4")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_40")
                        .HasColumnName("40")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_41")
                        .HasColumnName("41")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_42")
                        .HasColumnName("42")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_43")
                        .HasColumnName("43")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_44")
                        .HasColumnName("44")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_45")
                        .HasColumnName("45")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_46")
                        .HasColumnName("46")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_47")
                        .HasColumnName("47")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_48")
                        .HasColumnName("48")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_49")
                        .HasColumnName("49")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_5")
                        .HasColumnName("5")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_50")
                        .HasColumnName("50")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_51")
                        .HasColumnName("51")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_52")
                        .HasColumnName("52")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_53")
                        .HasColumnName("53")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_54")
                        .HasColumnName("54")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_55")
                        .HasColumnName("55")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_56")
                        .HasColumnName("56")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_57")
                        .HasColumnName("57")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_58")
                        .HasColumnName("58")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_59")
                        .HasColumnName("59")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_6")
                        .HasColumnName("6")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_60")
                        .HasColumnName("60")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_61")
                        .HasColumnName("61")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_62")
                        .HasColumnName("62")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_63")
                        .HasColumnName("63")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_64")
                        .HasColumnName("64")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_65")
                        .HasColumnName("65")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_66")
                        .HasColumnName("66")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_67")
                        .HasColumnName("67")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_68")
                        .HasColumnName("68")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_69")
                        .HasColumnName("69")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_7")
                        .HasColumnName("7")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_70")
                        .HasColumnName("70")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_71")
                        .HasColumnName("71")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_72")
                        .HasColumnName("72")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_73")
                        .HasColumnName("73")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_74")
                        .HasColumnName("74")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_75")
                        .HasColumnName("75")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_76")
                        .HasColumnName("76")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_77")
                        .HasColumnName("77")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_78")
                        .HasColumnName("78")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_79")
                        .HasColumnName("79")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_8")
                        .HasColumnName("8")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_80")
                        .HasColumnName("80")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_81")
                        .HasColumnName("81")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_82")
                        .HasColumnName("82")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_83")
                        .HasColumnName("83")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_84")
                        .HasColumnName("84")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_85")
                        .HasColumnName("85")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_86")
                        .HasColumnName("86")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_87")
                        .HasColumnName("87")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_88")
                        .HasColumnName("88")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_89")
                        .HasColumnName("89")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_9")
                        .HasColumnName("9")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_90")
                        .HasColumnName("90")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_91")
                        .HasColumnName("91")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_92")
                        .HasColumnName("92")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_93")
                        .HasColumnName("93")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_94")
                        .HasColumnName("94")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_95")
                        .HasColumnName("95")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_96")
                        .HasColumnName("96")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_97")
                        .HasColumnName("97")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_98")
                        .HasColumnName("98")
                        .HasColumnType("int(2)");

                    b.Property<int?>("_99")
                        .HasColumnName("99")
                        .HasColumnType("int(2)");

                    b.HasKey("DiemId")
                        .HasName("PRIMARY");

                    b.HasIndex("DiemId")
                        .HasName("DiemId");

                    b.ToTable("nhietdo");
                });

            modelBuilder.Entity("GloboWeather.WeatherManagement.Weather.weathercontext.Thoigian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("thoigian");
                });
#pragma warning restore 612, 618
        }
    }
}
