using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GloboWeather.WeatherManagement.Weather.Migrations
{
    public partial class ModifiedTableThoitiet : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "doamtb",
                columns: table => new
                {
                    DiemId = table.Column<string>(maxLength: 255, nullable: false),
                    RefDate = table.Column<DateTime>(type: "date", nullable: false),
                    _1 = table.Column<int>(name: "1", type: "int(2)", nullable: true),
                    _2 = table.Column<int>(name: "2", type: "int(2)", nullable: true),
                    _3 = table.Column<int>(name: "3", type: "int(2)", nullable: true),
                    _4 = table.Column<int>(name: "4", type: "int(2)", nullable: true),
                    _5 = table.Column<int>(name: "5", type: "int(2)", nullable: true),
                    _6 = table.Column<int>(name: "6", type: "int(2)", nullable: true),
                    _7 = table.Column<int>(name: "7", type: "int(2)", nullable: true),
                    _8 = table.Column<int>(name: "8", type: "int(2)", nullable: true),
                    _9 = table.Column<int>(name: "9", type: "int(2)", nullable: true),
                    _10 = table.Column<int>(name: "10", type: "int(2)", nullable: true),
                    _11 = table.Column<int>(name: "11", type: "int(2)", nullable: true),
                    _12 = table.Column<int>(name: "12", type: "int(2)", nullable: true),
                    _13 = table.Column<int>(name: "13", type: "int(2)", nullable: true),
                    _14 = table.Column<int>(name: "14", type: "int(2)", nullable: true),
                    _15 = table.Column<int>(name: "15", type: "int(2)", nullable: true),
                    _16 = table.Column<int>(name: "16", type: "int(2)", nullable: true),
                    _17 = table.Column<int>(name: "17", type: "int(2)", nullable: true),
                    _18 = table.Column<int>(name: "18", type: "int(2)", nullable: true),
                    _19 = table.Column<int>(name: "19", type: "int(2)", nullable: true),
                    _20 = table.Column<int>(name: "20", type: "int(2)", nullable: true),
                    _21 = table.Column<int>(name: "21", type: "int(2)", nullable: true),
                    _22 = table.Column<int>(name: "22", type: "int(2)", nullable: true),
                    _23 = table.Column<int>(name: "23", type: "int(2)", nullable: true),
                    _24 = table.Column<int>(name: "24", type: "int(2)", nullable: true),
                    _25 = table.Column<int>(name: "25", type: "int(2)", nullable: true),
                    _26 = table.Column<int>(name: "26", type: "int(2)", nullable: true),
                    _27 = table.Column<int>(name: "27", type: "int(2)", nullable: true),
                    _28 = table.Column<int>(name: "28", type: "int(2)", nullable: true),
                    _29 = table.Column<int>(name: "29", type: "int(2)", nullable: true),
                    _30 = table.Column<int>(name: "30", type: "int(2)", nullable: true),
                    _31 = table.Column<int>(name: "31", type: "int(2)", nullable: true),
                    _32 = table.Column<int>(name: "32", type: "int(2)", nullable: true),
                    _33 = table.Column<int>(name: "33", type: "int(2)", nullable: true),
                    _34 = table.Column<int>(name: "34", type: "int(2)", nullable: true),
                    _35 = table.Column<int>(name: "35", type: "int(2)", nullable: true),
                    _36 = table.Column<int>(name: "36", type: "int(2)", nullable: true),
                    _37 = table.Column<int>(name: "37", type: "int(2)", nullable: true),
                    _38 = table.Column<int>(name: "38", type: "int(2)", nullable: true),
                    _39 = table.Column<int>(name: "39", type: "int(2)", nullable: true),
                    _40 = table.Column<int>(name: "40", type: "int(2)", nullable: true),
                    _41 = table.Column<int>(name: "41", type: "int(2)", nullable: true),
                    _42 = table.Column<int>(name: "42", type: "int(2)", nullable: true),
                    _43 = table.Column<int>(name: "43", type: "int(2)", nullable: true),
                    _44 = table.Column<int>(name: "44", type: "int(2)", nullable: true),
                    _45 = table.Column<int>(name: "45", type: "int(2)", nullable: true),
                    _46 = table.Column<int>(name: "46", type: "int(2)", nullable: true),
                    _47 = table.Column<int>(name: "47", type: "int(2)", nullable: true),
                    _48 = table.Column<int>(name: "48", type: "int(2)", nullable: true),
                    _49 = table.Column<int>(name: "49", type: "int(2)", nullable: true),
                    _50 = table.Column<int>(name: "50", type: "int(2)", nullable: true),
                    _51 = table.Column<int>(name: "51", type: "int(2)", nullable: true),
                    _52 = table.Column<int>(name: "52", type: "int(2)", nullable: true),
                    _53 = table.Column<int>(name: "53", type: "int(2)", nullable: true),
                    _54 = table.Column<int>(name: "54", type: "int(2)", nullable: true),
                    _55 = table.Column<int>(name: "55", type: "int(2)", nullable: true),
                    _56 = table.Column<int>(name: "56", type: "int(2)", nullable: true),
                    _57 = table.Column<int>(name: "57", type: "int(2)", nullable: true),
                    _58 = table.Column<int>(name: "58", type: "int(2)", nullable: true),
                    _59 = table.Column<int>(name: "59", type: "int(2)", nullable: true),
                    _60 = table.Column<int>(name: "60", type: "int(2)", nullable: true),
                    _61 = table.Column<int>(name: "61", type: "int(2)", nullable: true),
                    _62 = table.Column<int>(name: "62", type: "int(2)", nullable: true),
                    _63 = table.Column<int>(name: "63", type: "int(2)", nullable: true),
                    _64 = table.Column<int>(name: "64", type: "int(2)", nullable: true),
                    _65 = table.Column<int>(name: "65", type: "int(2)", nullable: true),
                    _66 = table.Column<int>(name: "66", type: "int(2)", nullable: true),
                    _67 = table.Column<int>(name: "67", type: "int(2)", nullable: true),
                    _68 = table.Column<int>(name: "68", type: "int(2)", nullable: true),
                    _69 = table.Column<int>(name: "69", type: "int(2)", nullable: true),
                    _70 = table.Column<int>(name: "70", type: "int(2)", nullable: true),
                    _71 = table.Column<int>(name: "71", type: "int(2)", nullable: true),
                    _72 = table.Column<int>(name: "72", type: "int(2)", nullable: true),
                    _73 = table.Column<int>(name: "73", type: "int(2)", nullable: true),
                    _74 = table.Column<int>(name: "74", type: "int(2)", nullable: true),
                    _75 = table.Column<int>(name: "75", type: "int(2)", nullable: true),
                    _76 = table.Column<int>(name: "76", type: "int(2)", nullable: true),
                    _77 = table.Column<int>(name: "77", type: "int(2)", nullable: true),
                    _78 = table.Column<int>(name: "78", type: "int(2)", nullable: true),
                    _79 = table.Column<int>(name: "79", type: "int(2)", nullable: true),
                    _80 = table.Column<int>(name: "80", type: "int(2)", nullable: true),
                    _81 = table.Column<int>(name: "81", type: "int(2)", nullable: true),
                    _82 = table.Column<int>(name: "82", type: "int(2)", nullable: true),
                    _83 = table.Column<int>(name: "83", type: "int(2)", nullable: true),
                    _84 = table.Column<int>(name: "84", type: "int(2)", nullable: true),
                    _85 = table.Column<int>(name: "85", type: "int(2)", nullable: true),
                    _86 = table.Column<int>(name: "86", type: "int(2)", nullable: true),
                    _87 = table.Column<int>(name: "87", type: "int(2)", nullable: true),
                    _88 = table.Column<int>(name: "88", type: "int(2)", nullable: true),
                    _89 = table.Column<int>(name: "89", type: "int(2)", nullable: true),
                    _90 = table.Column<int>(name: "90", type: "int(2)", nullable: true),
                    _91 = table.Column<int>(name: "91", type: "int(2)", nullable: true),
                    _92 = table.Column<int>(name: "92", type: "int(2)", nullable: true),
                    _93 = table.Column<int>(name: "93", type: "int(2)", nullable: true),
                    _94 = table.Column<int>(name: "94", type: "int(2)", nullable: true),
                    _95 = table.Column<int>(name: "95", type: "int(2)", nullable: true),
                    _96 = table.Column<int>(name: "96", type: "int(2)", nullable: true),
                    _97 = table.Column<int>(name: "97", type: "int(2)", nullable: true),
                    _98 = table.Column<int>(name: "98", type: "int(2)", nullable: true),
                    _99 = table.Column<int>(name: "99", type: "int(2)", nullable: true),
                    _100 = table.Column<int>(name: "100", type: "int(2)", nullable: true),
                    _101 = table.Column<int>(name: "101", type: "int(2)", nullable: true),
                    _102 = table.Column<int>(name: "102", type: "int(2)", nullable: true),
                    _103 = table.Column<int>(name: "103", type: "int(2)", nullable: true),
                    _104 = table.Column<int>(name: "104", type: "int(2)", nullable: true),
                    _105 = table.Column<int>(name: "105", type: "int(2)", nullable: true),
                    _106 = table.Column<int>(name: "106", type: "int(2)", nullable: true),
                    _107 = table.Column<int>(name: "107", type: "int(2)", nullable: true),
                    _108 = table.Column<int>(name: "108", type: "int(2)", nullable: true),
                    _109 = table.Column<int>(name: "109", type: "int(2)", nullable: true),
                    _110 = table.Column<int>(name: "110", type: "int(2)", nullable: true),
                    _111 = table.Column<int>(name: "111", type: "int(2)", nullable: true),
                    _112 = table.Column<int>(name: "112", type: "int(2)", nullable: true),
                    _113 = table.Column<int>(name: "113", type: "int(2)", nullable: true),
                    _114 = table.Column<int>(name: "114", type: "int(2)", nullable: true),
                    _115 = table.Column<int>(name: "115", type: "int(2)", nullable: true),
                    _116 = table.Column<int>(name: "116", type: "int(2)", nullable: true),
                    _117 = table.Column<int>(name: "117", type: "int(2)", nullable: true),
                    _118 = table.Column<int>(name: "118", type: "int(2)", nullable: true),
                    _119 = table.Column<int>(name: "119", type: "int(2)", nullable: true),
                    _120 = table.Column<int>(name: "120", type: "int(2)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => x.DiemId);
                });

            migrationBuilder.CreateTable(
                name: "giogiat",
                columns: table => new
                {
                    DiemId = table.Column<string>(maxLength: 255, nullable: false),
                    RefDate = table.Column<DateTime>(type: "date", nullable: false),
                    _1 = table.Column<int>(name: "1", type: "int(2)", nullable: true),
                    _2 = table.Column<int>(name: "2", type: "int(2)", nullable: true),
                    _3 = table.Column<int>(name: "3", type: "int(2)", nullable: true),
                    _4 = table.Column<int>(name: "4", type: "int(2)", nullable: true),
                    _5 = table.Column<int>(name: "5", type: "int(2)", nullable: true),
                    _6 = table.Column<int>(name: "6", type: "int(2)", nullable: true),
                    _7 = table.Column<int>(name: "7", type: "int(2)", nullable: true),
                    _8 = table.Column<int>(name: "8", type: "int(2)", nullable: true),
                    _9 = table.Column<int>(name: "9", type: "int(2)", nullable: true),
                    _10 = table.Column<int>(name: "10", type: "int(2)", nullable: true),
                    _11 = table.Column<int>(name: "11", type: "int(2)", nullable: true),
                    _12 = table.Column<int>(name: "12", type: "int(2)", nullable: true),
                    _13 = table.Column<int>(name: "13", type: "int(2)", nullable: true),
                    _14 = table.Column<int>(name: "14", type: "int(2)", nullable: true),
                    _15 = table.Column<int>(name: "15", type: "int(2)", nullable: true),
                    _16 = table.Column<int>(name: "16", type: "int(2)", nullable: true),
                    _17 = table.Column<int>(name: "17", type: "int(2)", nullable: true),
                    _18 = table.Column<int>(name: "18", type: "int(2)", nullable: true),
                    _19 = table.Column<int>(name: "19", type: "int(2)", nullable: true),
                    _20 = table.Column<int>(name: "20", type: "int(2)", nullable: true),
                    _21 = table.Column<int>(name: "21", type: "int(2)", nullable: true),
                    _22 = table.Column<int>(name: "22", type: "int(2)", nullable: true),
                    _23 = table.Column<int>(name: "23", type: "int(2)", nullable: true),
                    _24 = table.Column<int>(name: "24", type: "int(2)", nullable: true),
                    _25 = table.Column<int>(name: "25", type: "int(2)", nullable: true),
                    _26 = table.Column<int>(name: "26", type: "int(2)", nullable: true),
                    _27 = table.Column<int>(name: "27", type: "int(2)", nullable: true),
                    _28 = table.Column<int>(name: "28", type: "int(2)", nullable: true),
                    _29 = table.Column<int>(name: "29", type: "int(2)", nullable: true),
                    _30 = table.Column<int>(name: "30", type: "int(2)", nullable: true),
                    _31 = table.Column<int>(name: "31", type: "int(2)", nullable: true),
                    _32 = table.Column<int>(name: "32", type: "int(2)", nullable: true),
                    _33 = table.Column<int>(name: "33", type: "int(2)", nullable: true),
                    _34 = table.Column<int>(name: "34", type: "int(2)", nullable: true),
                    _35 = table.Column<int>(name: "35", type: "int(2)", nullable: true),
                    _36 = table.Column<int>(name: "36", type: "int(2)", nullable: true),
                    _37 = table.Column<int>(name: "37", type: "int(2)", nullable: true),
                    _38 = table.Column<int>(name: "38", type: "int(2)", nullable: true),
                    _39 = table.Column<int>(name: "39", type: "int(2)", nullable: true),
                    _40 = table.Column<int>(name: "40", type: "int(2)", nullable: true),
                    _41 = table.Column<int>(name: "41", type: "int(2)", nullable: true),
                    _42 = table.Column<int>(name: "42", type: "int(2)", nullable: true),
                    _43 = table.Column<int>(name: "43", type: "int(2)", nullable: true),
                    _44 = table.Column<int>(name: "44", type: "int(2)", nullable: true),
                    _45 = table.Column<int>(name: "45", type: "int(2)", nullable: true),
                    _46 = table.Column<int>(name: "46", type: "int(2)", nullable: true),
                    _47 = table.Column<int>(name: "47", type: "int(2)", nullable: true),
                    _48 = table.Column<int>(name: "48", type: "int(2)", nullable: true),
                    _49 = table.Column<int>(name: "49", type: "int(2)", nullable: true),
                    _50 = table.Column<int>(name: "50", type: "int(2)", nullable: true),
                    _51 = table.Column<int>(name: "51", type: "int(2)", nullable: true),
                    _52 = table.Column<int>(name: "52", type: "int(2)", nullable: true),
                    _53 = table.Column<int>(name: "53", type: "int(2)", nullable: true),
                    _54 = table.Column<int>(name: "54", type: "int(2)", nullable: true),
                    _55 = table.Column<int>(name: "55", type: "int(2)", nullable: true),
                    _56 = table.Column<int>(name: "56", type: "int(2)", nullable: true),
                    _57 = table.Column<int>(name: "57", type: "int(2)", nullable: true),
                    _58 = table.Column<int>(name: "58", type: "int(2)", nullable: true),
                    _59 = table.Column<int>(name: "59", type: "int(2)", nullable: true),
                    _60 = table.Column<int>(name: "60", type: "int(2)", nullable: true),
                    _61 = table.Column<int>(name: "61", type: "int(2)", nullable: true),
                    _62 = table.Column<int>(name: "62", type: "int(2)", nullable: true),
                    _63 = table.Column<int>(name: "63", type: "int(2)", nullable: true),
                    _64 = table.Column<int>(name: "64", type: "int(2)", nullable: true),
                    _65 = table.Column<int>(name: "65", type: "int(2)", nullable: true),
                    _66 = table.Column<int>(name: "66", type: "int(2)", nullable: true),
                    _67 = table.Column<int>(name: "67", type: "int(2)", nullable: true),
                    _68 = table.Column<int>(name: "68", type: "int(2)", nullable: true),
                    _69 = table.Column<int>(name: "69", type: "int(2)", nullable: true),
                    _70 = table.Column<int>(name: "70", type: "int(2)", nullable: true),
                    _71 = table.Column<int>(name: "71", type: "int(2)", nullable: true),
                    _72 = table.Column<int>(name: "72", type: "int(2)", nullable: true),
                    _73 = table.Column<int>(name: "73", type: "int(2)", nullable: true),
                    _74 = table.Column<int>(name: "74", type: "int(2)", nullable: true),
                    _75 = table.Column<int>(name: "75", type: "int(2)", nullable: true),
                    _76 = table.Column<int>(name: "76", type: "int(2)", nullable: true),
                    _77 = table.Column<int>(name: "77", type: "int(2)", nullable: true),
                    _78 = table.Column<int>(name: "78", type: "int(2)", nullable: true),
                    _79 = table.Column<int>(name: "79", type: "int(2)", nullable: true),
                    _80 = table.Column<int>(name: "80", type: "int(2)", nullable: true),
                    _81 = table.Column<int>(name: "81", type: "int(2)", nullable: true),
                    _82 = table.Column<int>(name: "82", type: "int(2)", nullable: true),
                    _83 = table.Column<int>(name: "83", type: "int(2)", nullable: true),
                    _84 = table.Column<int>(name: "84", type: "int(2)", nullable: true),
                    _85 = table.Column<int>(name: "85", type: "int(2)", nullable: true),
                    _86 = table.Column<int>(name: "86", type: "int(2)", nullable: true),
                    _87 = table.Column<int>(name: "87", type: "int(2)", nullable: true),
                    _88 = table.Column<int>(name: "88", type: "int(2)", nullable: true),
                    _89 = table.Column<int>(name: "89", type: "int(2)", nullable: true),
                    _90 = table.Column<int>(name: "90", type: "int(2)", nullable: true),
                    _91 = table.Column<int>(name: "91", type: "int(2)", nullable: true),
                    _92 = table.Column<int>(name: "92", type: "int(2)", nullable: true),
                    _93 = table.Column<int>(name: "93", type: "int(2)", nullable: true),
                    _94 = table.Column<int>(name: "94", type: "int(2)", nullable: true),
                    _95 = table.Column<int>(name: "95", type: "int(2)", nullable: true),
                    _96 = table.Column<int>(name: "96", type: "int(2)", nullable: true),
                    _97 = table.Column<int>(name: "97", type: "int(2)", nullable: true),
                    _98 = table.Column<int>(name: "98", type: "int(2)", nullable: true),
                    _99 = table.Column<int>(name: "99", type: "int(2)", nullable: true),
                    _100 = table.Column<int>(name: "100", type: "int(2)", nullable: true),
                    _101 = table.Column<int>(name: "101", type: "int(2)", nullable: true),
                    _102 = table.Column<int>(name: "102", type: "int(2)", nullable: true),
                    _103 = table.Column<int>(name: "103", type: "int(2)", nullable: true),
                    _104 = table.Column<int>(name: "104", type: "int(2)", nullable: true),
                    _105 = table.Column<int>(name: "105", type: "int(2)", nullable: true),
                    _106 = table.Column<int>(name: "106", type: "int(2)", nullable: true),
                    _107 = table.Column<int>(name: "107", type: "int(2)", nullable: true),
                    _108 = table.Column<int>(name: "108", type: "int(2)", nullable: true),
                    _109 = table.Column<int>(name: "109", type: "int(2)", nullable: true),
                    _110 = table.Column<int>(name: "110", type: "int(2)", nullable: true),
                    _111 = table.Column<int>(name: "111", type: "int(2)", nullable: true),
                    _112 = table.Column<int>(name: "112", type: "int(2)", nullable: true),
                    _113 = table.Column<int>(name: "113", type: "int(2)", nullable: true),
                    _114 = table.Column<int>(name: "114", type: "int(2)", nullable: true),
                    _115 = table.Column<int>(name: "115", type: "int(2)", nullable: true),
                    _116 = table.Column<int>(name: "116", type: "int(2)", nullable: true),
                    _117 = table.Column<int>(name: "117", type: "int(2)", nullable: true),
                    _118 = table.Column<int>(name: "118", type: "int(2)", nullable: true),
                    _119 = table.Column<int>(name: "119", type: "int(2)", nullable: true),
                    _120 = table.Column<int>(name: "120", type: "int(2)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => x.DiemId);
                });

            migrationBuilder.CreateTable(
                name: "luongmua",
                columns: table => new
                {
                    DiemId = table.Column<string>(maxLength: 255, nullable: false),
                    RefDate = table.Column<DateTime>(type: "date", nullable: false),
                    _1 = table.Column<int>(name: "1", type: "int(2)", nullable: true),
                    _2 = table.Column<int>(name: "2", type: "int(2)", nullable: true),
                    _3 = table.Column<int>(name: "3", type: "int(2)", nullable: true),
                    _4 = table.Column<int>(name: "4", type: "int(2)", nullable: true),
                    _5 = table.Column<int>(name: "5", type: "int(2)", nullable: true),
                    _6 = table.Column<int>(name: "6", type: "int(2)", nullable: true),
                    _7 = table.Column<int>(name: "7", type: "int(2)", nullable: true),
                    _8 = table.Column<int>(name: "8", type: "int(2)", nullable: true),
                    _9 = table.Column<int>(name: "9", type: "int(2)", nullable: true),
                    _10 = table.Column<int>(name: "10", type: "int(2)", nullable: true),
                    _11 = table.Column<int>(name: "11", type: "int(2)", nullable: true),
                    _12 = table.Column<int>(name: "12", type: "int(2)", nullable: true),
                    _13 = table.Column<int>(name: "13", type: "int(2)", nullable: true),
                    _14 = table.Column<int>(name: "14", type: "int(2)", nullable: true),
                    _15 = table.Column<int>(name: "15", type: "int(2)", nullable: true),
                    _16 = table.Column<int>(name: "16", type: "int(2)", nullable: true),
                    _17 = table.Column<int>(name: "17", type: "int(2)", nullable: true),
                    _18 = table.Column<int>(name: "18", type: "int(2)", nullable: true),
                    _19 = table.Column<int>(name: "19", type: "int(2)", nullable: true),
                    _20 = table.Column<int>(name: "20", type: "int(2)", nullable: true),
                    _21 = table.Column<int>(name: "21", type: "int(2)", nullable: true),
                    _22 = table.Column<int>(name: "22", type: "int(2)", nullable: true),
                    _23 = table.Column<int>(name: "23", type: "int(2)", nullable: true),
                    _24 = table.Column<int>(name: "24", type: "int(2)", nullable: true),
                    _25 = table.Column<int>(name: "25", type: "int(2)", nullable: true),
                    _26 = table.Column<int>(name: "26", type: "int(2)", nullable: true),
                    _27 = table.Column<int>(name: "27", type: "int(2)", nullable: true),
                    _28 = table.Column<int>(name: "28", type: "int(2)", nullable: true),
                    _29 = table.Column<int>(name: "29", type: "int(2)", nullable: true),
                    _30 = table.Column<int>(name: "30", type: "int(2)", nullable: true),
                    _31 = table.Column<int>(name: "31", type: "int(2)", nullable: true),
                    _32 = table.Column<int>(name: "32", type: "int(2)", nullable: true),
                    _33 = table.Column<int>(name: "33", type: "int(2)", nullable: true),
                    _34 = table.Column<int>(name: "34", type: "int(2)", nullable: true),
                    _35 = table.Column<int>(name: "35", type: "int(2)", nullable: true),
                    _36 = table.Column<int>(name: "36", type: "int(2)", nullable: true),
                    _37 = table.Column<int>(name: "37", type: "int(2)", nullable: true),
                    _38 = table.Column<int>(name: "38", type: "int(2)", nullable: true),
                    _39 = table.Column<int>(name: "39", type: "int(2)", nullable: true),
                    _40 = table.Column<int>(name: "40", type: "int(2)", nullable: true),
                    _41 = table.Column<int>(name: "41", type: "int(2)", nullable: true),
                    _42 = table.Column<int>(name: "42", type: "int(2)", nullable: true),
                    _43 = table.Column<int>(name: "43", type: "int(2)", nullable: true),
                    _44 = table.Column<int>(name: "44", type: "int(2)", nullable: true),
                    _45 = table.Column<int>(name: "45", type: "int(2)", nullable: true),
                    _46 = table.Column<int>(name: "46", type: "int(2)", nullable: true),
                    _47 = table.Column<int>(name: "47", type: "int(2)", nullable: true),
                    _48 = table.Column<int>(name: "48", type: "int(2)", nullable: true),
                    _49 = table.Column<int>(name: "49", type: "int(2)", nullable: true),
                    _50 = table.Column<int>(name: "50", type: "int(2)", nullable: true),
                    _51 = table.Column<int>(name: "51", type: "int(2)", nullable: true),
                    _52 = table.Column<int>(name: "52", type: "int(2)", nullable: true),
                    _53 = table.Column<int>(name: "53", type: "int(2)", nullable: true),
                    _54 = table.Column<int>(name: "54", type: "int(2)", nullable: true),
                    _55 = table.Column<int>(name: "55", type: "int(2)", nullable: true),
                    _56 = table.Column<int>(name: "56", type: "int(2)", nullable: true),
                    _57 = table.Column<int>(name: "57", type: "int(2)", nullable: true),
                    _58 = table.Column<int>(name: "58", type: "int(2)", nullable: true),
                    _59 = table.Column<int>(name: "59", type: "int(2)", nullable: true),
                    _60 = table.Column<int>(name: "60", type: "int(2)", nullable: true),
                    _61 = table.Column<int>(name: "61", type: "int(2)", nullable: true),
                    _62 = table.Column<int>(name: "62", type: "int(2)", nullable: true),
                    _63 = table.Column<int>(name: "63", type: "int(2)", nullable: true),
                    _64 = table.Column<int>(name: "64", type: "int(2)", nullable: true),
                    _65 = table.Column<int>(name: "65", type: "int(2)", nullable: true),
                    _66 = table.Column<int>(name: "66", type: "int(2)", nullable: true),
                    _67 = table.Column<int>(name: "67", type: "int(2)", nullable: true),
                    _68 = table.Column<int>(name: "68", type: "int(2)", nullable: true),
                    _69 = table.Column<int>(name: "69", type: "int(2)", nullable: true),
                    _70 = table.Column<int>(name: "70", type: "int(2)", nullable: true),
                    _71 = table.Column<int>(name: "71", type: "int(2)", nullable: true),
                    _72 = table.Column<int>(name: "72", type: "int(2)", nullable: true),
                    _73 = table.Column<int>(name: "73", type: "int(2)", nullable: true),
                    _74 = table.Column<int>(name: "74", type: "int(2)", nullable: true),
                    _75 = table.Column<int>(name: "75", type: "int(2)", nullable: true),
                    _76 = table.Column<int>(name: "76", type: "int(2)", nullable: true),
                    _77 = table.Column<int>(name: "77", type: "int(2)", nullable: true),
                    _78 = table.Column<int>(name: "78", type: "int(2)", nullable: true),
                    _79 = table.Column<int>(name: "79", type: "int(2)", nullable: true),
                    _80 = table.Column<int>(name: "80", type: "int(2)", nullable: true),
                    _81 = table.Column<int>(name: "81", type: "int(2)", nullable: true),
                    _82 = table.Column<int>(name: "82", type: "int(2)", nullable: true),
                    _83 = table.Column<int>(name: "83", type: "int(2)", nullable: true),
                    _84 = table.Column<int>(name: "84", type: "int(2)", nullable: true),
                    _85 = table.Column<int>(name: "85", type: "int(2)", nullable: true),
                    _86 = table.Column<int>(name: "86", type: "int(2)", nullable: true),
                    _87 = table.Column<int>(name: "87", type: "int(2)", nullable: true),
                    _88 = table.Column<int>(name: "88", type: "int(2)", nullable: true),
                    _89 = table.Column<int>(name: "89", type: "int(2)", nullable: true),
                    _90 = table.Column<int>(name: "90", type: "int(2)", nullable: true),
                    _91 = table.Column<int>(name: "91", type: "int(2)", nullable: true),
                    _92 = table.Column<int>(name: "92", type: "int(2)", nullable: true),
                    _93 = table.Column<int>(name: "93", type: "int(2)", nullable: true),
                    _94 = table.Column<int>(name: "94", type: "int(2)", nullable: true),
                    _95 = table.Column<int>(name: "95", type: "int(2)", nullable: true),
                    _96 = table.Column<int>(name: "96", type: "int(2)", nullable: true),
                    _97 = table.Column<int>(name: "97", type: "int(2)", nullable: true),
                    _98 = table.Column<int>(name: "98", type: "int(2)", nullable: true),
                    _99 = table.Column<int>(name: "99", type: "int(2)", nullable: true),
                    _100 = table.Column<int>(name: "100", type: "int(2)", nullable: true),
                    _101 = table.Column<int>(name: "101", type: "int(2)", nullable: true),
                    _102 = table.Column<int>(name: "102", type: "int(2)", nullable: true),
                    _103 = table.Column<int>(name: "103", type: "int(2)", nullable: true),
                    _104 = table.Column<int>(name: "104", type: "int(2)", nullable: true),
                    _105 = table.Column<int>(name: "105", type: "int(2)", nullable: true),
                    _106 = table.Column<int>(name: "106", type: "int(2)", nullable: true),
                    _107 = table.Column<int>(name: "107", type: "int(2)", nullable: true),
                    _108 = table.Column<int>(name: "108", type: "int(2)", nullable: true),
                    _109 = table.Column<int>(name: "109", type: "int(2)", nullable: true),
                    _110 = table.Column<int>(name: "110", type: "int(2)", nullable: true),
                    _111 = table.Column<int>(name: "111", type: "int(2)", nullable: true),
                    _112 = table.Column<int>(name: "112", type: "int(2)", nullable: true),
                    _113 = table.Column<int>(name: "113", type: "int(2)", nullable: true),
                    _114 = table.Column<int>(name: "114", type: "int(2)", nullable: true),
                    _115 = table.Column<int>(name: "115", type: "int(2)", nullable: true),
                    _116 = table.Column<int>(name: "116", type: "int(2)", nullable: true),
                    _117 = table.Column<int>(name: "117", type: "int(2)", nullable: true),
                    _118 = table.Column<int>(name: "118", type: "int(2)", nullable: true),
                    _119 = table.Column<int>(name: "119", type: "int(2)", nullable: true),
                    _120 = table.Column<int>(name: "120", type: "int(2)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => x.DiemId);
                });

            migrationBuilder.CreateTable(
                name: "thoitiet",
                columns: table => new
                {
                    DiemId = table.Column<string>(maxLength: 255, nullable: false),
                    RefDate = table.Column<DateTime>(nullable: false),
                    _1 = table.Column<string>(name: "1", type: "varchar(10)", nullable: true),
                    _2 = table.Column<string>(name: "2", type: "varchar(10)", nullable: true),
                    _3 = table.Column<string>(name: "3", type: "varchar(10)", nullable: true),
                    _4 = table.Column<string>(name: "4", type: "varchar(10)", nullable: true),
                    _5 = table.Column<string>(name: "5", type: "varchar(10)", nullable: true),
                    _6 = table.Column<string>(name: "6", type: "varchar(10)", nullable: true),
                    _7 = table.Column<string>(name: "7", type: "varchar(10)", nullable: true),
                    _8 = table.Column<string>(name: "8", type: "varchar(10)", nullable: true),
                    _9 = table.Column<string>(name: "9", type: "varchar(10)", nullable: true),
                    _10 = table.Column<string>(name: "10", type: "varchar(10)", nullable: true),
                    _11 = table.Column<string>(name: "11", type: "varchar(10)", nullable: true),
                    _12 = table.Column<string>(name: "12", type: "varchar(10)", nullable: true),
                    _13 = table.Column<string>(name: "13", type: "varchar(10)", nullable: true),
                    _14 = table.Column<string>(name: "14", type: "varchar(10)", nullable: true),
                    _15 = table.Column<string>(name: "15", type: "varchar(10)", nullable: true),
                    _16 = table.Column<string>(name: "16", type: "varchar(10)", nullable: true),
                    _17 = table.Column<string>(name: "17", type: "varchar(10)", nullable: true),
                    _18 = table.Column<string>(name: "18", type: "varchar(10)", nullable: true),
                    _19 = table.Column<string>(name: "19", type: "varchar(10)", nullable: true),
                    _20 = table.Column<string>(name: "20", type: "varchar(10)", nullable: true),
                    _21 = table.Column<string>(name: "21", type: "varchar(10)", nullable: true),
                    _22 = table.Column<string>(name: "22", type: "varchar(10)", nullable: true),
                    _23 = table.Column<string>(name: "23", type: "varchar(10)", nullable: true),
                    _24 = table.Column<string>(name: "24", type: "varchar(10)", nullable: true),
                    _25 = table.Column<string>(name: "25", type: "varchar(10)", nullable: true),
                    _26 = table.Column<string>(name: "26", type: "varchar(10)", nullable: true),
                    _27 = table.Column<string>(name: "27", type: "varchar(10)", nullable: true),
                    _28 = table.Column<string>(name: "28", type: "varchar(10)", nullable: true),
                    _29 = table.Column<string>(name: "29", type: "varchar(10)", nullable: true),
                    _30 = table.Column<string>(name: "30", type: "varchar(10)", nullable: true),
                    _31 = table.Column<string>(name: "31", type: "varchar(10)", nullable: true),
                    _32 = table.Column<string>(name: "32", type: "varchar(10)", nullable: true),
                    _33 = table.Column<string>(name: "33", type: "varchar(10)", nullable: true),
                    _34 = table.Column<string>(name: "34", type: "varchar(10)", nullable: true),
                    _35 = table.Column<string>(name: "35", type: "varchar(10)", nullable: true),
                    _36 = table.Column<string>(name: "36", type: "varchar(10)", nullable: true),
                    _37 = table.Column<string>(name: "37", type: "varchar(10)", nullable: true),
                    _38 = table.Column<string>(name: "38", type: "varchar(10)", nullable: true),
                    _39 = table.Column<string>(name: "39", type: "varchar(10)", nullable: true),
                    _40 = table.Column<string>(name: "40", type: "varchar(10)", nullable: true),
                    _41 = table.Column<string>(name: "41", type: "varchar(10)", nullable: true),
                    _42 = table.Column<string>(name: "42", type: "varchar(10)", nullable: true),
                    _43 = table.Column<string>(name: "43", type: "varchar(10)", nullable: true),
                    _44 = table.Column<string>(name: "44", type: "varchar(10)", nullable: true),
                    _45 = table.Column<string>(name: "45", type: "varchar(10)", nullable: true),
                    _46 = table.Column<string>(name: "46", type: "varchar(10)", nullable: true),
                    _47 = table.Column<string>(name: "47", type: "varchar(10)", nullable: true),
                    _48 = table.Column<string>(name: "48", type: "varchar(10)", nullable: true),
                    _49 = table.Column<string>(name: "49", type: "varchar(10)", nullable: true),
                    _50 = table.Column<string>(name: "50", type: "varchar(10)", nullable: true),
                    _51 = table.Column<string>(name: "51", type: "varchar(10)", nullable: true),
                    _52 = table.Column<string>(name: "52", type: "varchar(10)", nullable: true),
                    _53 = table.Column<string>(name: "53", type: "varchar(10)", nullable: true),
                    _54 = table.Column<string>(name: "54", type: "varchar(10)", nullable: true),
                    _55 = table.Column<string>(name: "55", type: "varchar(10)", nullable: true),
                    _56 = table.Column<string>(name: "56", type: "varchar(10)", nullable: true),
                    _57 = table.Column<string>(name: "57", type: "varchar(10)", nullable: true),
                    _58 = table.Column<string>(name: "58", type: "varchar(10)", nullable: true),
                    _59 = table.Column<string>(name: "59", type: "varchar(10)", nullable: true),
                    _60 = table.Column<string>(name: "60", type: "varchar(10)", nullable: true),
                    _61 = table.Column<string>(name: "61", type: "varchar(10)", nullable: true),
                    _62 = table.Column<string>(name: "62", type: "varchar(10)", nullable: true),
                    _63 = table.Column<string>(name: "63", type: "varchar(10)", nullable: true),
                    _64 = table.Column<string>(name: "64", type: "varchar(10)", nullable: true),
                    _65 = table.Column<string>(name: "65", type: "varchar(10)", nullable: true),
                    _66 = table.Column<string>(name: "66", type: "varchar(10)", nullable: true),
                    _67 = table.Column<string>(name: "67", type: "varchar(10)", nullable: true),
                    _68 = table.Column<string>(name: "68", type: "varchar(10)", nullable: true),
                    _69 = table.Column<string>(name: "69", type: "varchar(10)", nullable: true),
                    _70 = table.Column<string>(name: "70", type: "varchar(10)", nullable: true),
                    _71 = table.Column<string>(name: "71", type: "varchar(10)", nullable: true),
                    _72 = table.Column<string>(name: "72", type: "varchar(10)", nullable: true),
                    _73 = table.Column<string>(name: "73", type: "varchar(10)", nullable: true),
                    _74 = table.Column<string>(name: "74", type: "varchar(10)", nullable: true),
                    _75 = table.Column<string>(name: "75", type: "varchar(10)", nullable: true),
                    _76 = table.Column<string>(name: "76", type: "varchar(10)", nullable: true),
                    _77 = table.Column<string>(name: "77", type: "varchar(10)", nullable: true),
                    _78 = table.Column<string>(name: "78", type: "varchar(10)", nullable: true),
                    _79 = table.Column<string>(name: "79", type: "varchar(10)", nullable: true),
                    _80 = table.Column<string>(name: "80", type: "varchar(10)", nullable: true),
                    _81 = table.Column<string>(name: "81", type: "varchar(10)", nullable: true),
                    _82 = table.Column<string>(name: "82", type: "varchar(10)", nullable: true),
                    _83 = table.Column<string>(name: "83", type: "varchar(10)", nullable: true),
                    _84 = table.Column<string>(name: "84", type: "varchar(10)", nullable: true),
                    _85 = table.Column<string>(name: "85", type: "varchar(10)", nullable: true),
                    _86 = table.Column<string>(name: "86", type: "varchar(10)", nullable: true),
                    _87 = table.Column<string>(name: "87", type: "varchar(10)", nullable: true),
                    _88 = table.Column<string>(name: "88", type: "varchar(10)", nullable: true),
                    _89 = table.Column<string>(name: "89", type: "varchar(10)", nullable: true),
                    _90 = table.Column<string>(name: "90", type: "varchar(10)", nullable: true),
                    _91 = table.Column<string>(name: "91", type: "varchar(10)", nullable: true),
                    _92 = table.Column<string>(name: "92", type: "varchar(10)", nullable: true),
                    _93 = table.Column<string>(name: "93", type: "varchar(10)", nullable: true),
                    _94 = table.Column<string>(name: "94", type: "varchar(10)", nullable: true),
                    _95 = table.Column<string>(name: "95", type: "varchar(10)", nullable: true),
                    _96 = table.Column<string>(name: "96", type: "varchar(10)", nullable: true),
                    _97 = table.Column<string>(name: "97", type: "varchar(10)", nullable: true),
                    _98 = table.Column<string>(name: "98", type: "varchar(10)", nullable: true),
                    _99 = table.Column<string>(name: "99", type: "varchar(10)", nullable: true),
                    _100 = table.Column<string>(name: "100", type: "varchar(10)", nullable: true),
                    _101 = table.Column<string>(name: "101", type: "varchar(10)", nullable: true),
                    _102 = table.Column<string>(name: "102", type: "varchar(10)", nullable: true),
                    _103 = table.Column<string>(name: "103", type: "varchar(10)", nullable: true),
                    _104 = table.Column<string>(name: "104", type: "varchar(10)", nullable: true),
                    _105 = table.Column<string>(name: "105", type: "varchar(10)", nullable: true),
                    _106 = table.Column<string>(name: "106", type: "varchar", nullable: true),
                    _107 = table.Column<string>(name: "107", type: "varchar(10)", nullable: true),
                    _108 = table.Column<string>(name: "108", type: "varchar(10)", nullable: true),
                    _109 = table.Column<string>(name: "109", type: "varchar(10)", nullable: true),
                    _110 = table.Column<string>(name: "110", type: "varchar(10)", nullable: true),
                    _111 = table.Column<string>(name: "111", type: "varchar(10)", nullable: true),
                    _112 = table.Column<string>(name: "112", type: "varchar(10)", nullable: true),
                    _113 = table.Column<string>(name: "113", type: "varchar(10)", nullable: true),
                    _114 = table.Column<string>(name: "114", type: "varchar(10)", nullable: true),
                    _115 = table.Column<string>(name: "115", type: "varchar(10)", nullable: true),
                    _116 = table.Column<string>(name: "116", type: "varchar(10)", nullable: true),
                    _117 = table.Column<string>(name: "117", type: "varchar(10)", nullable: true),
                    _118 = table.Column<string>(name: "118", type: "varchar(10)", nullable: true),
                    _119 = table.Column<string>(name: "119", type: "varchar(10)", nullable: true),
                    _120 = table.Column<string>(name: "120", type: "varchar(10)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => x.DiemId);
                });

            migrationBuilder.CreateTable(
                name: "tocdogio",
                columns: table => new
                {
                    DiemId = table.Column<string>(maxLength: 255, nullable: false),
                    RefDate = table.Column<DateTime>(type: "date", nullable: false),
                    _1 = table.Column<int>(name: "1", type: "int(2)", nullable: true),
                    _2 = table.Column<int>(name: "2", type: "int(2)", nullable: true),
                    _3 = table.Column<int>(name: "3", type: "int(2)", nullable: true),
                    _4 = table.Column<int>(name: "4", type: "int(2)", nullable: true),
                    _5 = table.Column<int>(name: "5", type: "int(2)", nullable: true),
                    _6 = table.Column<int>(name: "6", type: "int(2)", nullable: true),
                    _7 = table.Column<int>(name: "7", type: "int(2)", nullable: true),
                    _8 = table.Column<int>(name: "8", type: "int(2)", nullable: true),
                    _9 = table.Column<int>(name: "9", type: "int(2)", nullable: true),
                    _10 = table.Column<int>(name: "10", type: "int(2)", nullable: true),
                    _11 = table.Column<int>(name: "11", type: "int(2)", nullable: true),
                    _12 = table.Column<int>(name: "12", type: "int(2)", nullable: true),
                    _13 = table.Column<int>(name: "13", type: "int(2)", nullable: true),
                    _14 = table.Column<int>(name: "14", type: "int(2)", nullable: true),
                    _15 = table.Column<int>(name: "15", type: "int(2)", nullable: true),
                    _16 = table.Column<int>(name: "16", type: "int(2)", nullable: true),
                    _17 = table.Column<int>(name: "17", type: "int(2)", nullable: true),
                    _18 = table.Column<int>(name: "18", type: "int(2)", nullable: true),
                    _19 = table.Column<int>(name: "19", type: "int(2)", nullable: true),
                    _20 = table.Column<int>(name: "20", type: "int(2)", nullable: true),
                    _21 = table.Column<int>(name: "21", type: "int(2)", nullable: true),
                    _22 = table.Column<int>(name: "22", type: "int(2)", nullable: true),
                    _23 = table.Column<int>(name: "23", type: "int(2)", nullable: true),
                    _24 = table.Column<int>(name: "24", type: "int(2)", nullable: true),
                    _25 = table.Column<int>(name: "25", type: "int(2)", nullable: true),
                    _26 = table.Column<int>(name: "26", type: "int(2)", nullable: true),
                    _27 = table.Column<int>(name: "27", type: "int(2)", nullable: true),
                    _28 = table.Column<int>(name: "28", type: "int(2)", nullable: true),
                    _29 = table.Column<int>(name: "29", type: "int(2)", nullable: true),
                    _30 = table.Column<int>(name: "30", type: "int(2)", nullable: true),
                    _31 = table.Column<int>(name: "31", type: "int(2)", nullable: true),
                    _32 = table.Column<int>(name: "32", type: "int(2)", nullable: true),
                    _33 = table.Column<int>(name: "33", type: "int(2)", nullable: true),
                    _34 = table.Column<int>(name: "34", type: "int(2)", nullable: true),
                    _35 = table.Column<int>(name: "35", type: "int(2)", nullable: true),
                    _36 = table.Column<int>(name: "36", type: "int(2)", nullable: true),
                    _37 = table.Column<int>(name: "37", type: "int(2)", nullable: true),
                    _38 = table.Column<int>(name: "38", type: "int(2)", nullable: true),
                    _39 = table.Column<int>(name: "39", type: "int(2)", nullable: true),
                    _40 = table.Column<int>(name: "40", type: "int(2)", nullable: true),
                    _41 = table.Column<int>(name: "41", type: "int(2)", nullable: true),
                    _42 = table.Column<int>(name: "42", type: "int(2)", nullable: true),
                    _43 = table.Column<int>(name: "43", type: "int(2)", nullable: true),
                    _44 = table.Column<int>(name: "44", type: "int(2)", nullable: true),
                    _45 = table.Column<int>(name: "45", type: "int(2)", nullable: true),
                    _46 = table.Column<int>(name: "46", type: "int(2)", nullable: true),
                    _47 = table.Column<int>(name: "47", type: "int(2)", nullable: true),
                    _48 = table.Column<int>(name: "48", type: "int(2)", nullable: true),
                    _49 = table.Column<int>(name: "49", type: "int(2)", nullable: true),
                    _50 = table.Column<int>(name: "50", type: "int(2)", nullable: true),
                    _51 = table.Column<int>(name: "51", type: "int(2)", nullable: true),
                    _52 = table.Column<int>(name: "52", type: "int(2)", nullable: true),
                    _53 = table.Column<int>(name: "53", type: "int(2)", nullable: true),
                    _54 = table.Column<int>(name: "54", type: "int(2)", nullable: true),
                    _55 = table.Column<int>(name: "55", type: "int(2)", nullable: true),
                    _56 = table.Column<int>(name: "56", type: "int(2)", nullable: true),
                    _57 = table.Column<int>(name: "57", type: "int(2)", nullable: true),
                    _58 = table.Column<int>(name: "58", type: "int(2)", nullable: true),
                    _59 = table.Column<int>(name: "59", type: "int(2)", nullable: true),
                    _60 = table.Column<int>(name: "60", type: "int(2)", nullable: true),
                    _61 = table.Column<int>(name: "61", type: "int(2)", nullable: true),
                    _62 = table.Column<int>(name: "62", type: "int(2)", nullable: true),
                    _63 = table.Column<int>(name: "63", type: "int(2)", nullable: true),
                    _64 = table.Column<int>(name: "64", type: "int(2)", nullable: true),
                    _65 = table.Column<int>(name: "65", type: "int(2)", nullable: true),
                    _66 = table.Column<int>(name: "66", type: "int(2)", nullable: true),
                    _67 = table.Column<int>(name: "67", type: "int(2)", nullable: true),
                    _68 = table.Column<int>(name: "68", type: "int(2)", nullable: true),
                    _69 = table.Column<int>(name: "69", type: "int(2)", nullable: true),
                    _70 = table.Column<int>(name: "70", type: "int(2)", nullable: true),
                    _71 = table.Column<int>(name: "71", type: "int(2)", nullable: true),
                    _72 = table.Column<int>(name: "72", type: "int(2)", nullable: true),
                    _73 = table.Column<int>(name: "73", type: "int(2)", nullable: true),
                    _74 = table.Column<int>(name: "74", type: "int(2)", nullable: true),
                    _75 = table.Column<int>(name: "75", type: "int(2)", nullable: true),
                    _76 = table.Column<int>(name: "76", type: "int(2)", nullable: true),
                    _77 = table.Column<int>(name: "77", type: "int(2)", nullable: true),
                    _78 = table.Column<int>(name: "78", type: "int(2)", nullable: true),
                    _79 = table.Column<int>(name: "79", type: "int(2)", nullable: true),
                    _80 = table.Column<int>(name: "80", type: "int(2)", nullable: true),
                    _81 = table.Column<int>(name: "81", type: "int(2)", nullable: true),
                    _82 = table.Column<int>(name: "82", type: "int(2)", nullable: true),
                    _83 = table.Column<int>(name: "83", type: "int(2)", nullable: true),
                    _84 = table.Column<int>(name: "84", type: "int(2)", nullable: true),
                    _85 = table.Column<int>(name: "85", type: "int(2)", nullable: true),
                    _86 = table.Column<int>(name: "86", type: "int(2)", nullable: true),
                    _87 = table.Column<int>(name: "87", type: "int(2)", nullable: true),
                    _88 = table.Column<int>(name: "88", type: "int(2)", nullable: true),
                    _89 = table.Column<int>(name: "89", type: "int(2)", nullable: true),
                    _90 = table.Column<int>(name: "90", type: "int(2)", nullable: true),
                    _91 = table.Column<int>(name: "91", type: "int(2)", nullable: true),
                    _92 = table.Column<int>(name: "92", type: "int(2)", nullable: true),
                    _93 = table.Column<int>(name: "93", type: "int(2)", nullable: true),
                    _94 = table.Column<int>(name: "94", type: "int(2)", nullable: true),
                    _95 = table.Column<int>(name: "95", type: "int(2)", nullable: true),
                    _96 = table.Column<int>(name: "96", type: "int(2)", nullable: true),
                    _97 = table.Column<int>(name: "97", type: "int(2)", nullable: true),
                    _98 = table.Column<int>(name: "98", type: "int(2)", nullable: true),
                    _99 = table.Column<int>(name: "99", type: "int(2)", nullable: true),
                    _100 = table.Column<int>(name: "100", type: "int(2)", nullable: true),
                    _101 = table.Column<int>(name: "101", type: "int(2)", nullable: true),
                    _102 = table.Column<int>(name: "102", type: "int(2)", nullable: true),
                    _103 = table.Column<int>(name: "103", type: "int(2)", nullable: true),
                    _104 = table.Column<int>(name: "104", type: "int(2)", nullable: true),
                    _105 = table.Column<int>(name: "105", type: "int(2)", nullable: true),
                    _106 = table.Column<int>(name: "106", type: "int(2)", nullable: true),
                    _107 = table.Column<int>(name: "107", type: "int(2)", nullable: true),
                    _108 = table.Column<int>(name: "108", type: "int(2)", nullable: true),
                    _109 = table.Column<int>(name: "109", type: "int(2)", nullable: true),
                    _110 = table.Column<int>(name: "110", type: "int(2)", nullable: true),
                    _111 = table.Column<int>(name: "111", type: "int(2)", nullable: true),
                    _112 = table.Column<int>(name: "112", type: "int(2)", nullable: true),
                    _113 = table.Column<int>(name: "113", type: "int(2)", nullable: true),
                    _114 = table.Column<int>(name: "114", type: "int(2)", nullable: true),
                    _115 = table.Column<int>(name: "115", type: "int(2)", nullable: true),
                    _116 = table.Column<int>(name: "116", type: "int(2)", nullable: true),
                    _117 = table.Column<int>(name: "117", type: "int(2)", nullable: true),
                    _118 = table.Column<int>(name: "118", type: "int(2)", nullable: true),
                    _119 = table.Column<int>(name: "119", type: "int(2)", nullable: true),
                    _120 = table.Column<int>(name: "120", type: "int(2)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => x.DiemId);
                });

            migrationBuilder.CreateIndex(
                name: "DiemId",
                table: "doamtb",
                column: "DiemId");

            migrationBuilder.CreateIndex(
                name: "DiemId",
                table: "giogiat",
                column: "DiemId");

            migrationBuilder.CreateIndex(
                name: "DiemId",
                table: "luongmua",
                column: "DiemId");

            migrationBuilder.CreateIndex(
                name: "DiemId",
                table: "thoitiet",
                column: "DiemId");

            migrationBuilder.CreateIndex(
                name: "DiemId",
                table: "tocdogio",
                column: "DiemId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "doamtb");

            migrationBuilder.DropTable(
                name: "giogiat");

            migrationBuilder.DropTable(
                name: "luongmua");

            migrationBuilder.DropTable(
                name: "thoitiet");

            migrationBuilder.DropTable(
                name: "tocdogio");
        }
    }
}
